development:
  adapter: sqlite3
  database: <%= Mack::Paths.db("fake_application.db") %>

test:
  adapter: sqlite3
  database: <%= Mack::Paths.db("fake_application.db") %>

production:
  adapter: sqlite3
  database: <%= Mack::Paths.db("fake_application.db") %>