development:
  adapter: sqlite3
  database: <%= File.join(Mack::Configuration.root, "db", "fake_application.db") %>

test:
  adapter: sqlite3
  database: <%= File.join(Mack::Configuration.root, "db", "fake_application.db") %>

production:
  adapter: sqlite3
  database: <%= File.join(Mack::Configuration.root, "db", "fake_application.db") %>