development:
  adapter: sqlite3
  database: db/fake_application_development.db 
    
test:
  adapter: sqlite3
  database: <%= File.join(Mack::Configuration.root, "db", "fake_application_test.db") %>

production:
  adapter: sqlite3
  database: db/fake_application_production.db
