# mack::log_level: error

whiny_config_missing: false

foo: bar

mack::page_cache: true

mack::use_distributed_routes: false
mack::distributed_app_name: fake_app

# cachetastic_default_options:
#   logging:
#     logger_1:
#       type: console
#       level: debug