development:
  default:
    adapter: mysql
    database: mack_data_mapper_development
    host: localhost
    username: root
    password: 
    
test:
  default:
    adapter: mysql
    database: mack_data_mapper_test
    host: localhost
    username: root
    password:

production:
  default:
    adapter: mysql
    database: mack_data_mapper_production
    host: localhost
    username: root
    password:
